### ISSUE TITLE
reverse rotation direction in mandalas

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#100]
For some reason most symbols with a "direction" - like legs, oroboros, etc. - would look better if rotating counter-clockwise rather than clockwise. Then the legs could look like they're running, the oroboros eating its tail, etc. Easiest would just be to globally re-set rotation direction from clockwise to counter-clockwise.

**Comment by corinna000** [comment]
Grace, Nina, and I are working this issue.

**Comment by corinna000** [comment]
fixed in https://github.com/mysticsymbolic/mysticsymbolic.github.io/pull/103
