### ISSUE TITLE
Create/Edit code of conduct

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#106]
Hey @corinna000 , @graceolivia , @mittimithai , @webaissance , @toolness ,

I just put a **first draft** of a code of conduct (which we need in order to get netlify) at https://github.com/mysticsymbolic/mysticsymbolic.github.io/blob/main/code-o-conduct

Please edit, comment, etc.  Thanks!

**Comment by ninapaley** [comment]
I have shortened and tidied up the Code o' Conduct. Please review @toolness .

**Comment by toolness** [comment]
It looks good to me, I converted it to markdown so it's pretty and stuff!  I guess I will close this issue now, but you can re-open it if you think it needs more work.
