### ISSUE TITLE
Gradients, Tints, and Transparencies

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#121]
@toolness How much work would be required to develop support for color gradients in symbols/assets?
What about transparencies?
I mentioned in issue #31 that old Flash allowed "tinting" -- applying a %age of a chosen color to instances of symbols. Can that be done with SVGs?

If gradients were supported, could the program generate its own gradient backgrounds? Or gradient fills?
@mittimithai

**Comment by toolness** [comment]
Oh I think we could probably support this with some work!  Can you upload an SVG with a gradient to this issue, which you'd like to use as a symbol?  (It should have specs and stuff in it too.)  Then I can try working on supporting it.

Making the gradients actually manipulable by the color palette choices might be a bit harder.  I wonder if the gradient could somehow be based on the stroke, fill, and/or background color?  For example, what if all gradients had to use black and white, our stand-ins for stroke and fill?  Or would that be way too restrictive?

**Comment by ninapaley** [comment]
I made some new tree and hill assets with black and white gradients, and put them in the "landscape" folder. They're also attached here. They have specs layers too, so once there's support for gradients we can plop them into the "symbols" folder as well and see what happens.
[BWgradients.zip](https://github.com/mysticsymbolic/mysticsymbolic.github.io/files/6505438/BWgradients.zip)

**Comment by ninapaley** [comment]
One thing about specifying gradients with black and white: The whole symbol is limited to a pair of colors. Example:
![gradient_BW_example](https://user-images.githubusercontent.com/79212762/118831295-4607a780-b885-11eb-80c9-a52169f97216.png)
Here's a tree with a black-and-white gradient fill on the "foliage" and a solid black fill on the trunk.

![gradient_colors_example](https://user-images.githubusercontent.com/79212762/118831143-207a9e00-b885-11eb-96ca-845b0e9006c1.png)
Here is how we might color it with two shades of green, the lighter applied to white and the darker applied to black. The trunk is the same color as the darkest green.

![gradient_native_example](https://user-images.githubusercontent.com/79212762/118831527-78b1a000-b885-11eb-9d39-f5f76bfd2454.png)
Here is how I originally colored the tree, with a gradient of two greens for the foliage, and a completely different brown color for the trunk. I would not be able to do this using the black-and-white gradient spec system.

Now, is this a problem? Not really - I can certainly work with this 2-color restriction, because we will have multiple symbol instances in a single image, and between them some procedural color modulation or "jitter" as @mittimithai calls it. So as pieces of a whole composition, 2-color symbols like this should still look good, and sometimes restrictions like this can just be part of the "style." But I did want to make a note of it to see if you had any thoughts @toolness .

**Comment by ninapaley** [comment]
Well look I solved my own problem, just by taking a shower and thinking about what @mittimithai said about narrower gradient ranges. Whether I interpreted him correctly I do not know, but I re-did the same tree with a less extreme gradient:
![gradient_BW_subtler](https://user-images.githubusercontent.com/79212762/118885296-33a96000-b8bd-11eb-9511-0cc15d430599.png)
Instead of going all the way from white to black, it goes from white to some shade of gray. Then I replaced white with a lightish green, and black with a dark brown, and voila: 
![gradient_browngreen](https://user-images.githubusercontent.com/79212762/118885410-58053c80-b8bd-11eb-8096-8ca4aa60e1f1.png)
This is very close to my original tree coloring, and only uses two colors. So yay! The black and white gradient system should do everything I want.

**Comment by mittimithai** [comment]
Cool. So only selecting three colors (the ways things are now) and assigning them to the color points on the radial gradient produces the intended effect, correct?

One other option to consider is leave the template as black and white (all the gradient is defining is the type as "radial" and that there are two points) the first point is just the base color (say that green) and the other gradient point is a jittered version of that base color (maybe even a jittered version a certain way, here it might have to be darker).

**Comment by ninapaley** [comment]
> Cool. So only selecting three colors (the ways things are now) and assigning them to the color points on the radial gradient produces the intended effect, correct?
> 

Yes it does!

> One other option to consider is leave the template as black and white (all the gradient is defining is the type as "radial" and that there are two points) the first point is just the base color (say that green) and the other gradient point is a jittered version of that base color (maybe even a jittered version a certain way, here it might have to be darker).

Wow! We have a lot of options, then. As the Background Generator comes together, we can try a lot of color things on the trees.
