### ISSUE TITLE
gradients fail in symbols folder

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#134]
@toolness I added gradients to some symbols and uploaded them to the "symbols" assets folder and got the big red "X" in actions. Confusingly, the gradients do show up when I examine the symbol in the repository (ie antler.svg) but the gradients don't show up in the Creature or Mandala.

**Comment by toolness** [comment]
Ah, that's because it's a linear gradient!  The previous SVGs you provided all used radial gradients, so I was only able to add support for those... now that I have an example of how moho generates a linear gradient I will add support for that.

**Comment by toolness** [comment]
Ok, it should be fixed now!
