### ISSUE TITLE
some gradients not showing up on "swap stroke/fill"

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#138]
Randomizer yielded this symbol coloring, with gradient:
![Screen Shot 2021-05-29 at 6 33 16 PM](https://user-images.githubusercontent.com/79212762/120087329-84cf0600-c0ac-11eb-963d-852b9a261878.png)
When I clicked "swap stroke/fill" it rendered thusly:
![Screen Shot 2021-05-29 at 6 33 24 PM](https://user-images.githubusercontent.com/79212762/120087337-91ebf500-c0ac-11eb-97c9-10becd77b61e.png)
"Cathedral" still shows a gradient after swapping, while "circle_spiral" does not. Just thought you should know @toolness .

**Comment by toolness** [comment]
Oh it looks like this is actually technically a bug with the SVG!  Looking at its source, it seems the "black" color is not actually black, but `rgb(22,22,22)`--so _really_ close to black, but not actually black.  This means that the program won't think of it as the fill color, and will instead think of it as a color to "pass through" (i.e. not do anything with), which is what it does with e.g. the colors in `rainbow_half`.

If you change the color to actually be 100% black then everything should work!

**Comment by ninapaley** [comment]
Yup I just figured this out! Fixed.
