### ISSUE TITLE
Consider requiring that all code contributions be submitted as pull requests

### ISSUE THREAD

**Issue by toolness** [mysticsymbolic/mysticsymbolic.github.io#153]
As our base of contributors grows, the stability of our `main` branch becomes more important.

For example, last week @ninapaley added an SVG to the `main` branch that broke the build (see #144).  This then impacted the work of @webaissance, who merged `main` into his branch in #145, and also my work on #146 (I had to fix the broken build in f2553177a9d3d23723959c976479f8897baf5300 in order to make any new PRs).

This isn't to blame @ninapaley of course--making changes directly to `main` via the GitHub website's UI is the only way I taught her how to make changes!  But it might be time to teach her how to create a pull request, safely making all her changes in a branch, and only merging it into `main` when the test suite passes, ensuring that the build never breaks.  Now that we have Netlify integration, this shouldn't actually change her workflow much, since she can easily see the Netlify deploy preview to see the effects of any changes she makes.

This will have the additional benefit of hopefully cleaning up our [commit history](https://github.com/mysticsymbolic/mysticsymbolic.github.io/commits/main) a bit--right now there's a ton of not-very-informative "Add files via upload" commits in there, and with the symbol changes "batched" into PRs it might make it less spammy.

**Comment by toolness** [comment]
@ninapaley if you want to play around with this idea, I _think_ it should be fairly straightforward... when you upload files or edit them in the GitHub website, choose the "Create a new branch for this commit and start a pull request" option:

> ![image](https://user-images.githubusercontent.com/124687/121014449-fcb1c600-c767-11eb-97d2-4b5108fdfa4b.png)

Once you've got a branch, you can make further changes to it directly by visiting the branch.  You can visit your branch by clicking on its branch name in the pull request that was created for it.  For example, here's Dave's PR:

> ![image](https://user-images.githubusercontent.com/124687/121014697-426e8e80-c768-11eb-975c-338eee18e0b9.png)

Clicking on `webaissance:main` will take you to Dave's branch.  It will look a whole lot like browsing the `main` branch except it won't be on `main`.  You can then use the "upload files" functionality (or edit files functionality) to make further changes; when you do, the first option in the "commit changes" section will say "Commit directly to `ninapaley-patch-1`" (or whatever the name of your branch is) and you can choose that.  The changes you make will then be added to your PR's branch, rather than `main`, allowing you to iterate in your own "sandbox" (which you can view via Netlify's deploy preview).  Then once you are happy with your changes you can click the "Squash and merge" button at the bottom of the PR to merge it into `main`, which will make it go live on the website.

If any of that is confusing, no worries, I can explain/demo it at our next meeting!

**Comment by ninapaley** [comment]
Thanks @toolness  for the explanation and instructions! This makes sense and I wish I'd been doing it earlier. I will definitely make a branch for any modifications I make moving forward.

**Comment by toolness** [comment]
@ninapaley is now making pull requests like a pro and it's working great!  🎉  So, I'm closing this issue.
