### ISSUE TITLE
Allow for symbols to be excluded

### ISSUE THREAD

**Issue by abetusk** [mysticsymbolic/mysticsymbolic.github.io#173]
It would be nice to have an option to exclude symbols, preferably more than one at a time.

There's a "Always include this symbol" option in the "creatures" section, so this seems like a natural extension.

For example, as much as I love J.R., perhaps I would want him excluded from the generative process.

**Comment by toolness** [comment]
Hi @abetusk!  Sorry I didn't reply to this earlier, this seems like a reasonable idea--is there a reason you closed it?
