### ISSUE TITLE
"never_attach" or "always_center" symbols

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#176]
Some symbols should never be attached to other symbols (especially these new Tarot archetypes I'm designing). For symbols that should never be nested, we have
`never_be_nested`
Can we also have
`never_attach` or `always_center`
The goal is to have a symbol only be in the center of a creature whenever it shows up. I tried forcing this by removing the anchor point of angel.svg, but the result was, when I selected it under "always include this symbol," that most of time it just didn't show up at all.

**Comment by toolness** [comment]
I can do that!  Hmm, is an alternative to just treat any symbols without anchor points as being `never_attach`-ed/`always_center`-ed?  I kind of like that approach, it feels more elegant and simpler, but if you prefer I can just implement a new metadata property too.

**Comment by ninapaley** [comment]
@toolness The anchor point might be useful when the same symbol is in the Mandala, or animated in some future application, so for that reason using toml metadata might be better than just getting rid of the anchor point.

**Comment by toolness** [comment]
Oh ok will do!  Do you have a preference of `never_attach` vs. `always_center`?  I feel like `never_attach` might be an ambiguous name b/c it could be interpreted as meaning "never attach anything to this symbol" or "never use this symbol as an attachment to other symbols"...

Internally, the creature code has a concept called a ["root symbol"](https://github.com/mysticsymbolic/mysticsymbolic.github.io/blob/b68bc9726f63afa3c74d842efb4a776d732d3da1/lib/pages/creature-page.tsx#L44-L45), which is a symbol that can be used as the main body of a creature.  So one possible name for it could be `use_only_as_root`, unless that sounds weird...

**Comment by ninapaley** [comment]
`use_only_as_root` sounds perfect. Thanks!

**Comment by toolness** [comment]
Oh wait, I just thought of an even easier thing that I _think_ doesn't even involve changing our code... I already added `attach_to` in #52:

```toml
# If set to an array of strings, this indicates the kinds of
# attachment points that this symbol can attach to.  If not
# defined, this symbol will be able to attach to any attachment
# point.
attach_to = ["tail", "leg", "arm", "horn", "crown"]
```

I think you should be able to just set this to an empty array, i.e.:

```toml
attach_to = []
```

That ensures that the symbol is never used as an attachment to anything else.  I actually just looked through our repository and it looks like you've never used this property so maybe it slipped your mind?  Or maybe when I added support for it, it got spamfiltered on your end?

Anyways, I just edited a symbol and set its `attach_to = []` and this indeed did what I said above.  If this is good for you, feel free to close this issue.

**Comment by ninapaley** [comment]
BY GOLLY IT WORKS!

Thanks @toolness !
