### ISSUE TITLE
Influence symbol frequency

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#191]
Suppose I wanted some symbols - like the wings - to show up more often than they do. Because I have restricted the points wings can attach to, they show up less frequently than symbols that attach promiscuously to everything. Could there be a line I could add to the wings' TOMLs that would boost their frequency and increase their statistical likelihood of appearing in a creature, while still attaching only to certain points? @toolness

**Comment by toolness** [comment]
Hmm good question. So one thing that we could do is have a kind of frequency "multiplier".  It could be the equivalent of just adding a bunch of copies of the same symbol to the vocabulary--for instance, if you wanted `wing.svg` to be more frequent, one extremely brute-force way to do it without actually coding anything would be to make copies of the file--`wing2.svg`, `wing3.svg` etc--and simply by virtue of the fact that there are more of the exact same symbol present in the `assets/symbols` directory, it would be more common in creatures.

Obviously that's a huge hassle though!  So one way to "shortcut" the same kind of behavior might be to add a line like this to `wing.toml`:

```
frequency_multiplier = 50
```

That would make it seem as though there were 50 copies of that symbol in the vocabulary, making it effectively 50 times more likely that a wing would be chosen as an attachment.  However, the exact probability changes as the vocabulary size fluctuates... a `frequency_multiplier` would have far more impact in a vocabulary of just two symbols than in one of, um, 269--holy cow that's how many symbols we have right now!! 🤯

**Comment by ninapaley** [comment]
269 symbols? Heh, I've been busy. That's not even including all the ones I tried out and deleted. 

I like frequency_multiplier, if it's not too hard to implement! Is there an upper limit to the multiplier value?

**Comment by toolness** [comment]
Hmm that is a good question, lemme do some research on what the best way to implement this would be and get back to you--I suspect the naive approach I was planning on using might not be ideal for huge `frequency_multiplier` values.
