### ISSUE TITLE
palette algorithm with 3 random hues

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#193]
Right now the default "threevals" palette algorithm picks a hue at random, sets a second hue x degrees away, and picks a third hue 180° from the midpoint between them. @mittimithai can you make a branch wherein you duplicate the threevals algorithm but ditch the hue angles (but keep the values part!), and just use 3 random hues? As soon as you submit a pull request I should be able to see whether it works better than what we have now.

**Comment by mittimithai** [comment]
Take a look at: https://deploy-preview-194--quizzical-swanson-c06190.netlify.app/

**Comment by ninapaley** [comment]
@mittimithai Thanks! Yes! I like "randhue" in addition to "threevals". @toolness can you check this and merge if appropriate?

**Comment by toolness** [comment]
Oh #194 was merged! Closing this.
