### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#26]
Let users save "creature" images to a gallery. Part of the save process requires entering a title. I am having fun naming my screenshots, adding a title almost makes it poetry.

**Comment by toolness** [comment]
Ideas brought up during brainstorming:

* Random "artist statement" feature.
* Require contributors to come up w/ a title for the composition b/c it's so much fun.
* Allow anonymous contributions.

**Comment by ninapaley** [comment]
This is how I imagine the Gallery dialog box should look:
![gallery submission dialog](https://user-images.githubusercontent.com/79212762/114884375-57175180-9dcb-11eb-9a43-7580f75ef9e0.jpeg)
There will be a "submit to gallery" button at MysticSymbolic. When the user clicks it, the above dialog appears, and whatever image they made gets submitted via some process created by @toolness and @webaissance .

The user can enter a title and artist/author name; those boxes are lightly pre-filled with "Untitled" and "Unknown", respectively, indicating that if they don't enter anything that's what the image will be called. 

Hopefully an "I am not a robot" checkbox will reduce bot abuse, somehow. 
There is a potential for spammer abuse, where people enter crappy urls for title or artist, or abusive titles like "kill all TERFs", but I don't think we should worry about that until it happens. I don't want to discourage URLs or social media handles in the "by" box, yet.

Speaking of social media handles, we should also have E-Z "share" buttons on gallery images! Or even on main MysticSymbolic pages. Buttons could include:

- export SVG
- export PNG
- share to Gallery
- share to social media (twitter, fecebook, instagram, fediverse account, etc.)

**Comment by ninapaley** [comment]
As for the Random Artist Statement, maybe we could link with this: https://www.artybollocks.com/generator.html
The "short artist statement" on the lower right would be ideal.

But oh noes! It says, "Copyright © 2011-2018. All rights reserved." That sucks.
Maybe they'd be willing to share anyway. They do have this page: https://www.artybollocks.com/bollocks-in-practice.html

**Comment by webaissance** [comment]
Cool.  Thanks for this Nina.  I will think about implementations and work
with the team on it.
-Dave

**Comment by toolness** [comment]
Ok @ninapaley we've got an _extremely_ barebones "gallery" in place now!  Unfortunately there are not yet any thumbnails, but you can click on each entry to be taken to the creature/mandala page with the composition pre-loaded in it (which is kind of neat because it allows you to "remix" other people's creations).  Will add actual thumbnails soon!

**Comment by ninapaley** [comment]
Cool @toolness !! Right now I see one link on the gallery page, to Atomic Braniac (nice). I also see the note that you're working on a way to submit to the gallery, I look forward to it!

**Comment by toolness** [comment]
Oops, sorry, that description was out of date--you can submit to it via the sidebar on the creature and mandala pages!

**Comment by ninapaley** [comment]
Yay it's working!
Now might be a good time to change "creature" to "composition."

**Comment by ninapaley** [comment]
How about "cluster"?

> Is there any other term you prefer other than "composition" that we could call a creature? Otherwise I'll have to figure out a different terminology to use within the code for a "composition" so that things don't get too confusing.

**Comment by toolness** [comment]
Nice, I like that!  Can you file an issue to rename "creature" to "cluster"?

**Comment by toolness** [comment]
Ok @ninapaley we've got thumbnails in the gallery now!  See #220 for more details and screenshots.

**Comment by toolness** [comment]
Hmm, so with the merging of #220 I feel like the "v1" of the gallery is done, so I'm going to go ahead and close this issue. @ninapaley if there's more/different things you'd like to see done with the gallery, please file a separate issue (or start a discussion in the Github Discussions area).  Thanks!
