### ISSUE TITLE
Add a "make sure this random creature has a particular symbol in it" feature

### ISSUE THREAD

**Issue by toolness** [mysticsymbolic/mysticsymbolic.github.io#36]
@ninapaley I was just thinking that it might be useful to have a feature in the creature page where you can specify e.g. "make sure the random creature has an antler somewhere in it".  This might make it easier for you to test symbols, I think, and it'd make it easier for me to ensure that the way I'm treating metadata works--e.g. I could make a bunch of creatures with the "eye" symbol and make sure that every one has something nested in the eyeball...

Anyways would this be useful for you?

**Comment by ninapaley** [comment]
Yes that would be useful!

My brain's a churnin', but I have to go on a bike ride while the afternoon is still young. More later!

**Comment by ninapaley** [comment]
It occurs to me that with this feature, if you limit your available vocabulary to just one symbol, you get fractaling!

As the library of symbols grows, this feature will become increasingly useful for my tests. Also it would be good to disable some symbols without having to delete them from the repository.
