### ISSUE TITLE
random color inversions

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#39]
Symbols have two colors: black and white. I started exporting inverted versions (black fills with white strokes) to mix up the look more. Can each symbol be generated with inverted colors, randomly? Essentially two versions of every symbol, but auto-generated instead of me having to make each one. Just duplicate the symbol and invert the colors.

**Comment by ninapaley** [comment]
Really what I should do is make all the symbols default white fills with black strokes, as before, and with the handy inversion-making code we can have 2 modes of creature: all with same white fills and black strokes OR a random equal-ish mix of white and black fills and strokes. OR all inverted, although the user can invert everything themselves using the color sliders. Does that make sense? Once the random color inversion feature is added, I'll go back and re-export all the symbols with white fills and black strokes.

**Comment by ninapaley** [comment]
I guess it doesn't even need to store 2 versions, just that it render a symbol either normal or inverted in random-but-more-or-less-equal frequency. Maybe symbols could have 3 modes: light (standard predominately white fill black strokes), dark (inverted to predominately black fills and white strokes) and mixed (randomly renders standard and inverted).

**Comment by toolness** [comment]
Ooo interesting, this should definitely be doable.  I just have to make sure I understand you right...

With regards to having the whole creature inverted, would it be helpful to have a "swap stroke/fill color" button, similar to how lots of art programs have a "swap foreground/background" color option?  That would make it really easy for the user to invert the colors themselves.

And then for the random-ish mix, are you basically saying that it would actually sort of work how it does right now, since you've added a bunch of inverted symbols manually and the current result is that it's randomly choosing between an inverted and non-inverted symbol?  Only with the addition of the code, it'd be done in a smart way so you wouldn't have to export an inverted version of each symbol manually?

**Comment by toolness** [comment]
Ok I just added a "swap stroke/fill color" button in 1824d7249b9ebdf2abc387877049988a61a38605.  I guess I just need to add a "randomly invert some symbols" checkbox now?

**Comment by ninapaley** [comment]
Ooh I like that swap stroke/fill button! But yes, "randomly invert some symbols" is what I really want. Once I revert the symbols to white fills/black strokes it will be more powerful. Right now many symbols are inverted (without renaming - only a few have _inv versions I bothered to name) and will be reverted tomorrow.

**Comment by toolness** [comment]
Nice!  Ok cool, actually this will be a bit easier for me to work on if your manually-inverted symbols are gone--that way I will be able to easily tell if my random-inversion code is actually working, vs. just happening to pick a manually-inverted symbol.  Let me know when you've cleared out the manually inverted symbols and I will add the randomizing code ASAP!

**Comment by ninapaley** [comment]
They’re all reverted to white fills and black strokes except for the ones with “inv” in their names, plus I think the”beast head”. Feel free to delete anything with “inv” in its name.

**Comment by ninapaley** [comment]
The “foot” might be black too. Please just delete those symbols for now, I will put everything back!

**Comment by ninapaley** [comment]
OK I have just deleted or reverted the remaining inverted symbols! (Sorry I couldn't do it last night - I was on my phone after a too-long bike ride.) Everything should be ready for the randomizing code. A few symbols have and will continue to have both black and white areas, like the lion head, impossible cube, and chair, and all the architectural bits with black-filled windows and doors.

**Comment by ninapaley** [comment]
Since many symbols show up in pairs, perhaps such pairs could have one black and one white of each.
![Snake Muscles](https://user-images.githubusercontent.com/79212762/110052054-8b074d80-7d1c-11eb-9073-69b0fcacd234.png)
In the illustration above, if one of each pair were inverted, it might make a nice composition. 
The only way to see if this works once everything is randomized is to try it and find out!

**Comment by ninapaley** [comment]
Can this be the next thing that gets worked on? It will help me as I continue to work on symbols.

**Comment by toolness** [comment]
Absolutely! I think I just implemented it in #43, it should be live on the website soon, let me know what you think!

**Comment by ninapaley** [comment]
Thanks! Can you make it so the nested symbols invert again, if their host is randomly inverted? Right now the nested symbol inversion is not preserved, per images below:
![Screen Shot 2021-03-06 at 9 04 50 PM](https://user-images.githubusercontent.com/79212762/110227618-cd1cc480-7ebf-11eb-9e8e-9183813754c1.png)
![Screen Shot 2021-03-06 at 9 04 28 PM](https://user-images.githubusercontent.com/79212762/110227619-cdb55b00-7ebf-11eb-8d66-23b142e326e8.png)

**Comment by ninapaley** [comment]
I'm reopening this issue so the inversion of nested symbols can be maintained. If a symbol is randomly inverted, any inverted symbol nested on it must be inverted again. That will restore a lot of much-needed black-white balance to the compositions.

**Comment by toolness** [comment]
Oh sorry about that! Ok I think I just fixed it... if that didn't do the trick, feel free to re-open this issue again.

**Comment by ninapaley** [comment]
Ahhh, that's better. Thanks.

**Comment by ninapaley** [comment]
Reopening this because I would like to see mixed pairs now. Pairs of symbols would show up as one black and one white. Triples would have at least one inverted.

> Since many symbols show up in pairs, perhaps such pairs could have one black and one white of each.
> ![Snake Muscles](https://user-images.githubusercontent.com/79212762/110052054-8b074d80-7d1c-11eb-9073-69b0fcacd234.png)
> In the screencap above, if one of each pair were inverted, it might make a nice composition. The only way to see if this works once everything is randomized is to try it and find out!
>
