### ISSUE TITLE
Symbols with fewer than 1 attachment points should never be the center of a creature

### ISSUE THREAD

**Issue by toolness** [mysticsymbolic/mysticsymbolic.github.io#45]
From #41:

> So, I would like a rule that says that symbols with fewer than, say, 4 attachment points (not counting the anchor point) are never the center of a creature.

**Comment by ninapaley** [comment]
An alternative would be a line I could add to the TOMLs that says "never_center = true". Then I could ensure certain other symbols are never centered, if I so desire...

**Comment by toolness** [comment]
Hey @webaissance, if you're interested in tackling this one, can you comment on this issue?  I'm trying to use GitHub's "assignees" feature to keep track of who's working on what, but apparently I can't set you as an assignee unless you've commented on the issue.

**Comment by webaissance** [comment]
Hmm. Interesting. I have commented on some issues - such as the Clouds Page.
Let me know if more is needed...

-Dave, Webaissance

**Comment by toolness** [comment]
Ok @ninapaley this is now fixed by #154!  Note, though, that at present, _all_ symbols seem to have at least one attachment point (exclusive of the anchor point), so it doesn't actually change anything as-is.  I guess it just means that you can create new symbols (or modify existing ones) without having to worry about them being used as the body of a creature if they only have an anchor point.

**Comment by ninapaley** [comment]
Heh, that's because every time I found such a symbol I added an attachment point to it. I should have made a note of that in this issue!
