### ISSUE TITLE
It should be possible to permalink to a creature/mandala/etc.

### ISSUE THREAD

**Issue by toolness** [mysticsymbolic/mysticsymbolic.github.io#61]
It would be neat if it were possible to permalink to a creature/mandala/etc, and even have the "randomize" button change the current URL to be a permalink so that one could use their browser's "back" button to  go back to a earlier design they might have accidentally skipped past.

Originally I was thinking that the permalink could just contain the random number seed used to randomly generate a composition, but this would be problematic for a number of reasons, not least of which is that our algorithm is constantly changing, so it wouldn't be a "permalink" so much as a "works-for-this-version-link".

Better would be to have all the parameters of the composition be editable, like the mandala currently is (see e.g. https://github.com/toolness/mystic-symbolic/issues/24#issuecomment-808896672), and have the randomize button just change the parameters in constrained ways.  Then the permalink could just be a serialization of the parameters, which, at the very least, are less likely to change from version to version compared to the procedural generation algorithm.

**Comment by ninapaley** [comment]
Yes yes yes! Great idea.
Will that help with the Gallery issue ( #26 ) too?

**Comment by toolness** [comment]
Yeah, I think so!  If we save the gallery "images" as little bags of data that give us just enough information to re-create the images, it would have a number of possibilities:

* **Compression!**  Each gallery image would be super tiny so we could store tons of them without using up much storage.
* **Remix-ability!**  Since each gallery image is essentially just a representation of all the slider/checkbox/dropdown/etc values used to construct them, it'd make it really easy for someone to remix (or "fork", which is the GitHub lingo that's caught on in recent years) in an intelligible way.
* **Update-ability!?**  This is potentially both a blessing and a curse.  If what a gallery image contains is really just a "pointer to" the eyeball symbol, for instance, this means that if you change the eyeball symbol, the gallery image will change too.  If we don't want that to happen, we might end up needing to "version" our symbols, so that the gallery entry could point to the "eyeball version 1" symbol.

**Comment by ninapaley** [comment]
Cool! But if it's easier to just save a PNG or SVG to the gallery, that's good too.

**Comment by toolness** [comment]
Ok I've just made mandalas permalink-able in #99!  The only thing to note here is that everything is stored in the URL bar, which isn't visible from @webaissance's version of the site, as it embeds the site in an iframe.  I guess this is one reason we might want to consider having the whole website be a React single-page application that uses a REST API written by @webaissance, rather than a PHP site that wraps the site in an iframe, but we can always discuss that later.

Anyways, here's an example of a mandala with one symbol:

https://mysticsymbolic.github.io/?p=mandala&s=AhhoYW5kX3JlbGF4ZWQAAFJDDgEAAIA%2FAAAAAAAAgD8AAAAAAACa9NAEjNmnAa71vwfNzAxAAABAQAEA

So the URLs aren't _too_ long (though the length increases if you add another circle).  And as I mention in #99, the URL changes every time you stop fiddling with the settings for a quarter of a second, which means that you can always e.g. press "back" if you accidentally skipped past a random design that looked cool, or if you make a few changes and decided it looked better the way it was, etc.

**Comment by toolness** [comment]
Ok, with #211 creatures are now permalinked to my satisfaction too, and with #212 we have more widget values being preserved as the user navigates through their browsing history too.  I'm going to go ahead and close this issue.
