### ISSUE TITLE
"Randomize Everything" on Creature page

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#70]
I'd like a button that randomizes color AND symbols on the "Creature" (which I'm personally thinking of as "Cluster") page. Heck, it could also randomize complexity level. Should always randomly invert symbols.

**Comment by ninapaley** [comment]
Randomize Everything would be nice on the Mandalas page too.

**Comment by toolness** [comment]
Oh this was fixed by #87!
