### ISSUE TITLE
Dr. Mesmer's Animatorium

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#71]
These animation cycles on the Mandalas page would be super excellent:

1. Symbol Rotation cycle: This would just endlessly loop the existing Rotate Symbols slider from 0 to 360°. This effect will work better on circles with larger radii, be they positive or negative. I predict this is both the easiest to implement and the most powerful animation.

2.  Radius expansion: a mandala's radius starts at -500, grows to +500, and continues growing until all the symbols on it have left the visible canvas area. This could go on forever as long as there's always a new mandala behind the current one. To start it could be exactly the same one, just staggered in time (ie, 8x goat_head.svg, expanding and disappearing over and over again while another exactly the same appears behind it.)

**Comment by toolness** [comment]
Ok I just added very basic support for symbol rotation animatin in #75!  See the animated GIF there for how it works.

Unfortunately there's still no way to export to animated GIF, or vary the speed of the animation, or do the radius expansion thing... and also, when you export the mandala, it now uses the visible canvas on your screen as the export area, i.e. it doesn't automatically crop the canvas to the area the symbols occupy like the creature creator does.  But it's a start!

**Comment by ninapaley** [comment]
AWWWWWW YEAHHHHHH.

A great start indeed, @toolness ! I plan to be mesmerized playing with it for a while.

**Comment by ninapaley** [comment]
Yup. That is mesmerizing all right.

**Comment by toolness** [comment]
Hehe nice!  🎉   I just added a duration slider, let me know what you think!

Next step is to make these exportable to animated GIFs so they're easy to share...

**Comment by toolness** [comment]
Just added animated GIF export in #79!  Let me know what you think @ninapaley.  The animation is currently locked at 15 frames per second but we can increase it to 24 or something else if you want.

**Comment by ninapaley** [comment]
@toolness Whoooah cooooollll!!! 
I suggest making the gifs export at half size to reduce file size. That might give them enough room to up the frame rate to 20 or 24.

**Comment by toolness** [comment]
Ok I'm going to go ahead and mark this as done, we can create separate issues for individual improvements.
