### ISSUE TITLE
Allow color randomization algorithm to be chosen

### ISSUE THREAD

**Issue by toolness** [mysticsymbolic/mysticsymbolic.github.io#95]
As suggested by @webaissance in https://github.com/mysticsymbolic/mysticsymbolic.github.io/issues/27#issuecomment-817215615:

> Might I suggest having an option for different color randomizer modes: a)
Totally random (original method) b) mittimithai method/s c) potentially
other methods (grayscale only, super saturated, pastel, custom palettes,
etc)

**Comment by webaissance** [comment]
Atul - you're amazing!
Nice job.
