### ISSUE TITLE
Make new folder in Assets for Compositions

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#96]
This would be assets/compositions . I will upload to it compositions such as tarot cards with mask ( #89 ) and the new arrows-and-outlined-bounding-box (#90 ) specs.

**Comment by toolness** [comment]
Ok I just created the directory in 4420b09!  Note that there's a single file in there called `.placeholder`--that's because git doesn't allow you to have empty directories, so I had to start it with one file in there.  Once you've uploaded a few files into that directory, feel free to delete it.
